CREATE DATABASE ECommerceDB

CREATE TABLE Customers(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
Email NVARCHAR(100),
Phone INT
)

CREATE TABLE Products(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
[Description] NVARCHAR(100),
Price INT
)

CREATE TABLE Categories(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
[Description] NVARCHAR(100)
)

CREATE TABLE Orders(
ID INT PRIMARY KEY IDENTITY(1,1),
OrderDate DATETIME,
Status NVARCHAR(100)
)

CREATE TABLE OrderItems(
ID INT PRIMARY KEY IDENTITY(1,1),
Quantity INT,
UnitPrice INT
)

CREATE TABLE Suppliers(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
ContactInfo NVARCHAR(100)
)

CREATE TABLE ProductSuppliers(
ID INT PRIMARY KEY IDENTITY(1,1)
)
