CREATE DATABASE ECommerceDB



CREATE TABLE Suppliers(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
ContactInfo NVARCHAR(100)
)

CREATE TABLE Categories(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
[Description] NVARCHAR(100)
)

CREATE TABLE Products(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
[Description] NVARCHAR(100),
Price INT,
CategoryID INT FOREIGN KEY REFERENCES Categories(ID),
SupplierID INT FOREIGN KEY REFERENCES Suppliers(ID)
)
 
CREATE TABLE ProductSuppliers(
ID INT PRIMARY KEY IDENTITY(1,1),
ProductID INT FOREIGN KEY REFERENCES Products(ID),
SupplierID INT FOREIGN KEY REFERENCES Suppliers(ID)
)



 CREATE TABLE Customers(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100),
Email NVARCHAR(100),
Phone INT
)

CREATE TABLE Orders(
ID INT PRIMARY KEY IDENTITY(1,1),
OrderDate DATETIME,
Status NVARCHAR(100),
CustomerID INT FOREIGN KEY REFERENCES Customers(ID) 
)

CREATE TABLE OrderItems(
ID INT PRIMARY KEY IDENTITY(1,1),
Quantity INT,
UnitPrice INT,
OrderID  INT FOREIGN KEY REFERENCES Orders(ID),
ProductID INT FOREIGN KEY REFERENCES Products(ID)
)



